type: object
properties:
  data:
    type: array
    items:
      id:
        type: integer
        description: Product ID
      name:
        type: string
        description: Product name
      price:
        type: string
        description: Product price
      quantity:
        type: integer
        description: Product stock quantity
      SKU:
        type: string
        description: Product SKU
      description:
        type: string
        description: Product description
      observaciones:
        type: string
        description: Product observaciones
      createdAt:
        type: string
        description: Product creation timestamp
      modifiedAt:
        type: string
        description: Product last modification timestamp
      deletedAt:
        type: string
        description: Product delete timestamp
      categoryId:
        type: string
        description: Product main category ID.
      brandId:
        type: string
        description: Product brand id.
  status:
    type: string
    example: OK